-- ============================================================================
-- Seed Icons Library
-- ============================================================================

INSERT INTO public.icons (emoji, name, category, keywords, sort_order) VALUES
-- Media & Entertainment
('🎬', 'Clapper Board', 'Media', 'movie film cinema video', 0),
('🎥', 'Movie Camera', 'Media', 'film video record', 1),
('📺', 'Television', 'Media', 'tv screen watch', 2),
('📹', 'Video Camera', 'Media', 'record film', 3),
('🎞️', 'Film Frames', 'Media', 'movie cinema', 4),
('📽️', 'Film Projector', 'Media', 'movie cinema', 5),
('🎙️', 'Studio Microphone', 'Media', 'podcast audio record', 6),
('🎧', 'Headphones', 'Media', 'audio music listen', 7),
('🎵', 'Musical Note', 'Media', 'music song audio', 8),
('🎶', 'Musical Notes', 'Media', 'music song audio', 9),
('🎤', 'Microphone', 'Media', 'sing karaoke audio', 10),
('📻', 'Radio', 'Media', 'audio broadcast', 11),
('🔊', 'Speaker High', 'Media', 'audio sound volume', 12),
('📢', 'Loudspeaker', 'Media', 'announcement broadcast', 13),

-- Gaming
('🎮', 'Video Game', 'Gaming', 'controller play gaming', 14),
('🕹️', 'Joystick', 'Gaming', 'arcade game play', 15),
('👾', 'Alien Monster', 'Gaming', 'game retro arcade', 16),
('🎯', 'Bullseye', 'Gaming', 'target aim goal', 17),
('🎲', 'Dice', 'Gaming', 'game chance luck', 18),
('♟️', 'Chess Pawn', 'Gaming', 'strategy board game', 19),
('🃏', 'Joker Card', 'Gaming', 'cards poker game', 20),
('🎰', 'Slot Machine', 'Gaming', 'casino gambling', 21),
('🏆', 'Trophy', 'Gaming', 'winner award champion', 22),
('🥇', 'Gold Medal', 'Gaming', 'winner first place', 23),

-- Technology
('💻', 'Laptop', 'Technology', 'computer code programming', 24),
('🖥️', 'Desktop', 'Technology', 'computer monitor screen', 25),
('📱', 'Smartphone', 'Technology', 'phone mobile device', 26),
('⌨️', 'Keyboard', 'Technology', 'type computer input', 27),
('🖱️', 'Mouse', 'Technology', 'computer click', 28),
('💾', 'Floppy Disk', 'Technology', 'save storage retro', 29),
('💿', 'CD', 'Technology', 'disc storage music', 30),
('📀', 'DVD', 'Technology', 'disc movie storage', 31),
('🔌', 'Electric Plug', 'Technology', 'power connect', 32),
('🔋', 'Battery', 'Technology', 'power energy charge', 33),
('📡', 'Satellite', 'Technology', 'signal broadcast', 34),
('🤖', 'Robot', 'Technology', 'ai automation bot', 35),
('⚙️', 'Gear', 'Technology', 'settings config mechanical', 36),
('🔧', 'Wrench', 'Technology', 'tool fix repair', 37),
('🛠️', 'Tools', 'Technology', 'fix repair build', 38),

-- Education & Learning
('📚', 'Books', 'Education', 'read study library', 39),
('📖', 'Open Book', 'Education', 'read study learn', 40),
('📝', 'Memo', 'Education', 'note write document', 41),
('✏️', 'Pencil', 'Education', 'write draw edit', 42),
('🎓', 'Graduation Cap', 'Education', 'school university learn', 43),
('🔬', 'Microscope', 'Education', 'science research lab', 44),
('🔭', 'Telescope', 'Education', 'space astronomy science', 45),
('🧪', 'Test Tube', 'Education', 'science chemistry lab', 46),
('🧬', 'DNA', 'Education', 'biology science genetics', 47),
('📐', 'Triangular Ruler', 'Education', 'math geometry', 48),
('📏', 'Ruler', 'Education', 'measure math', 49),
('🧮', 'Abacus', 'Education', 'math calculate count', 50),
('💡', 'Light Bulb', 'Education', 'idea innovation think', 51),
('🧠', 'Brain', 'Education', 'think smart intelligence', 52),

-- Sports & Fitness
('⚽', 'Soccer Ball', 'Sports', 'football sport game', 53),
('🏀', 'Basketball', 'Sports', 'sport game', 54),
('🏈', 'American Football', 'Sports', 'sport game nfl', 55),
('⚾', 'Baseball', 'Sports', 'sport game mlb', 56),
('🎾', 'Tennis', 'Sports', 'sport racket game', 57),
('🏐', 'Volleyball', 'Sports', 'sport game beach', 58),
('🏓', 'Ping Pong', 'Sports', 'table tennis sport', 59),
('🏒', 'Ice Hockey', 'Sports', 'sport game nhl', 60),
('⛳', 'Golf', 'Sports', 'sport game', 61),
('🏋️', 'Weight Lifting', 'Sports', 'gym fitness workout', 62),
('🚴', 'Cycling', 'Sports', 'bike fitness exercise', 63),
('🏃', 'Running', 'Sports', 'jog fitness exercise', 64),
('🧘', 'Yoga', 'Sports', 'meditation fitness relax', 65),
('🥊', 'Boxing Glove', 'Sports', 'fight mma sport', 66),
('🎿', 'Skiing', 'Sports', 'winter snow sport', 67),
('🏄', 'Surfing', 'Sports', 'beach ocean water sport', 68),

-- Food & Cooking
('🍳', 'Cooking', 'Food', 'breakfast egg fry', 69),
('🍕', 'Pizza', 'Food', 'italian food eat', 70),
('🍔', 'Burger', 'Food', 'fast food eat', 71),
('🍣', 'Sushi', 'Food', 'japanese food', 72),
('🍜', 'Noodles', 'Food', 'ramen asian food', 73),
('🍰', 'Cake', 'Food', 'dessert baking sweet', 74),
('☕', 'Coffee', 'Food', 'drink cafe morning', 75),
('🍷', 'Wine', 'Food', 'drink alcohol', 76),
('🍺', 'Beer', 'Food', 'drink alcohol', 77),
('🧁', 'Cupcake', 'Food', 'dessert baking sweet', 78),
('🥗', 'Salad', 'Food', 'healthy vegetable food', 79),
('🌮', 'Taco', 'Food', 'mexican food', 80),
('🥘', 'Paella', 'Food', 'cooking pot food', 81),
('👨‍🍳', 'Chef', 'Food', 'cook kitchen restaurant', 82),

-- Travel & Places
('✈️', 'Airplane', 'Travel', 'fly travel vacation', 83),
('🚗', 'Car', 'Travel', 'drive vehicle auto', 84),
('🚀', 'Rocket', 'Travel', 'space launch fly', 85),
('🚂', 'Train', 'Travel', 'railway transport', 86),
('🚢', 'Ship', 'Travel', 'boat cruise ocean', 87),
('🏠', 'House', 'Travel', 'home building', 88),
('🏢', 'Office Building', 'Travel', 'work business', 89),
('🏰', 'Castle', 'Travel', 'history medieval', 90),
('🗽', 'Statue of Liberty', 'Travel', 'usa new york landmark', 91),
('🗼', 'Tokyo Tower', 'Travel', 'japan landmark', 92),
('🌍', 'Globe Europe', 'Travel', 'earth world map', 93),
('🌎', 'Globe Americas', 'Travel', 'earth world map', 94),
('🏔️', 'Mountain', 'Travel', 'nature hiking outdoor', 95),
('🏖️', 'Beach', 'Travel', 'vacation ocean sun', 96),
('🌴', 'Palm Tree', 'Travel', 'tropical beach vacation', 97),
('⛺', 'Camping', 'Travel', 'outdoor nature tent', 98),

-- Nature & Animals
('🐶', 'Dog', 'Nature', 'pet animal puppy', 99),
('🐱', 'Cat', 'Nature', 'pet animal kitten', 100),
('🦁', 'Lion', 'Nature', 'animal wild safari', 101),
('🐼', 'Panda', 'Nature', 'animal cute bear', 102),
('🦊', 'Fox', 'Nature', 'animal wild', 103),
('🦋', 'Butterfly', 'Nature', 'insect nature', 104),
('🌸', 'Cherry Blossom', 'Nature', 'flower spring japan', 105),
('🌻', 'Sunflower', 'Nature', 'flower summer yellow', 106),
('🌲', 'Evergreen Tree', 'Nature', 'forest nature pine', 107),
('🌊', 'Wave', 'Nature', 'ocean sea water', 108),
('☀️', 'Sun', 'Nature', 'weather sunny bright', 109),
('🌙', 'Moon', 'Nature', 'night sky space', 110),
('⭐', 'Star', 'Nature', 'night sky space', 111),
('🔥', 'Fire', 'Nature', 'hot flame burn', 112),
('💧', 'Water Drop', 'Nature', 'rain liquid', 113),
('❄️', 'Snowflake', 'Nature', 'winter cold ice', 114),

-- Business & Finance
('💰', 'Money Bag', 'Business', 'finance rich wealth', 115),
('💵', 'Dollar', 'Business', 'money cash finance', 116),
('💳', 'Credit Card', 'Business', 'payment buy shopping', 117),
('📈', 'Chart Up', 'Business', 'stocks growth profit', 118),
('📊', 'Bar Chart', 'Business', 'data statistics', 119),
('💼', 'Briefcase', 'Business', 'work business job', 120),
('🏦', 'Bank', 'Business', 'money finance', 121),
('📋', 'Clipboard', 'Business', 'list document', 122),
('📌', 'Pushpin', 'Business', 'important note', 123),
('📎', 'Paperclip', 'Business', 'attach document', 124),
('✅', 'Check Mark', 'Business', 'done complete yes', 125),
('❌', 'Cross Mark', 'Business', 'no cancel wrong', 126),
('🔒', 'Lock', 'Business', 'secure private', 127),
('🔑', 'Key', 'Business', 'unlock access', 128),

-- Art & Creative
('🎨', 'Artist Palette', 'Creative', 'paint art draw color', 129),
('🖌️', 'Paintbrush', 'Creative', 'paint art draw', 130),
('✒️', 'Ink Pen', 'Creative', 'write calligraphy', 131),
('🖊️', 'Pen', 'Creative', 'write draw sign', 132),
('📷', 'Camera', 'Creative', 'photo picture shoot', 133),
('📸', 'Camera Flash', 'Creative', 'photo picture', 134),
('🎭', 'Theater Masks', 'Creative', 'drama acting performance', 135),
('🎪', 'Circus Tent', 'Creative', 'entertainment show', 136),
('🎡', 'Ferris Wheel', 'Creative', 'amusement park fun', 137),
('🎠', 'Carousel', 'Creative', 'amusement park fun', 138),
('🎹', 'Piano', 'Creative', 'music keyboard instrument', 139),
('🎸', 'Guitar', 'Creative', 'music rock instrument', 140),
('🎺', 'Trumpet', 'Creative', 'music brass instrument', 141),
('🎻', 'Violin', 'Creative', 'music classical instrument', 142),
('🥁', 'Drum', 'Creative', 'music percussion beat', 143),

-- People & Lifestyle
('👨‍💻', 'Technologist', 'People', 'developer coder programmer', 144),
('👩‍🔬', 'Scientist', 'People', 'research lab science', 145),
('👨‍🎨', 'Artist', 'People', 'creative paint draw', 146),
('👩‍🏫', 'Teacher', 'People', 'education school learn', 147),
('👨‍⚕️', 'Doctor', 'People', 'health medical', 148),
('🦷', 'Tooth', 'People', 'teeth dental dentist health', 149),
('👷', 'Construction', 'People', 'worker build', 150),
('👨‍🌾', 'Farmer', 'People', 'agriculture garden', 151),
('🧑‍🚀', 'Astronaut', 'People', 'space nasa', 152),
('💪', 'Flexed Biceps', 'People', 'strong muscle power', 153),
('👍', 'Thumbs Up', 'People', 'like approve good', 154),
('🙌', 'Raising Hands', 'People', 'celebrate praise', 155),
('👏', 'Clapping', 'People', 'applause bravo', 156),
('🤝', 'Handshake', 'People', 'deal agree', 157),
('❤️', 'Red Heart', 'People', 'love like favorite', 158),
('😀', 'Grinning Face', 'People', 'happy smile joy', 159),
('😎', 'Cool Face', 'People', 'sunglasses awesome', 160);
